-- vim.lsp.config("rust_analyzer", {
--   settings = {
--     ["rust-analyzer"] = {
--       check = {
--         command = "check",
--       },
--     },
--   },
-- })

-- vim.g.rustaceanvim = {
--   server = {
--     default_settings = {
--       ["rust-analyzer"] = {
--         check = {
--           command = "check",
--         },
--       },
--     },
--   },
-- }
